spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${REPO_URI}
          refresh-rate: 15
          timeout: 5
          search-paths: 'configuration/,configuration/{application}/{profile}'
          username: ${USERNAME}
          password: ${PASSWORD}
server:
  port: 8888

encrypt:
  key: ${ENCRYPT_KEY}
